### ISSUE TITLE
Caddy PHP Docker article - open 9000 port and the kinsing malware

### ISSUE THREAD

**Issue by Humphreybas** [netsensei/colada#20]
This might not be the best place for this message since this repo is not about the content of your website but the tech behind it(?), but I couldn't find you contact details so I am posting it here.

When searching online how to implement caddy+php on docker I found your article as a good start:
https://www.colada.be/caddy-php-and-docker.html

However today I found some strange logs in my PHP-FPM container.  Also my CPU usage went up to 100%. Upon researching this I found out it must be some atack related to the kinsing malware. (for example I got some hints from [this thread](https://github.com/roundcube/roundcubemail-docker/issues/129)).

I copied your config in my docker compose and that got me in trouble.

```
    php:
        container_name: php
        image: php:7.4-fpm-alpine
        volumes:
            - app:/var/www/html
        networks:
            - phpapp
        ports:
            - 9000:9000

```
You are exposing the 9000 port on the PHP-FPM container to the 9000 port on the host computer. So to the outside world, which is not needed. 

Since both containers (php and caddy) are on the same docker network (phpapp) you can just omit the whole port definition on the php container so the port will only be open to the internal docker network.
